if (typeof(Storage) !== "undefined") {
osc="function O(i){return typeof i==\'object\' ? i : document.getElementById(i)};function S(i){return O(i).style};function C(i){return document.getElementsByClassname(i)};";
dom="function $(id){return document.getElementById(id)};function $(name){document.getElementsByTagName(name)};function $(name){document.getElementsByClassName(name)};";
mainFrag="const mainFragment=document.createDocumentFragment();const footer=mainFragment.appendChild(document.createElement('main'))\n.appendChild(document.createElement('header'))\n.appendChild(document.createElement('nav'))\n.appendChild(document.createElement('div'))\n.appendChild(document.createElement('footer'));footer.textContent='footer';footer.style='text-align:center;';document.body.appendChild(mainFragment);";
topBtn="const design=document.createElement('style');design.innerHTML='#topBtn{display:none;position:fixed;bottom:21px;right:23px;z-index:99;font-size:18px;border:none;outline:none;background-color:red;color:white;cursor:pointer;padding:15px;border-radius:4px;}#topBtn:hover{background-color:#555;}';head=document.getElementsByTagName('head')[0];head.appendChild(design);var button=document.createElement('button');button.innerHTML='Top';button.setAttribute('id', 'topBtn');button.addEventListener('click', topFunction);document.body.appendChild(button);window.onscroll=function(){scrollFunction()};function scrollFunction(){if(document.body.scrollTop>20||document.documentElement.scrollTop>20){button.style='display:block;';}else{button.style.display='none';}}function topFunction(){document.body.scrollTop=0;/*For Safari*/document.documentElement.scrollTop=0;}/*For Chrome, Firefox, IE and Opera*/";
uuId="const uuid=uuId();function uuId() {return \'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx\'.replace(/[xy]/g, function(c) {var r = Math.random() * 16 | 0, v = c == \'x\' ? r : (r & 0x3 | 0x8);return v.toString(16); }); }";
tst="let str='<ul><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><hr><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li><li>.</li></ul>'; let foo=document.getElementsByTagName('footer')[0]; let bar=foo.parentNode; let helper=document.createElement('div'); helper.innerHTML=str; while (helper.firstChild) {bar.insertBefore(helper.firstChild, foo); }";
localStorage.setItem('needles', JSON.stringify(osc+dom+topBtn+uuId));
localStorage.setItem('admin', 111213);
localStorage.setItem('storageLength', localStorage.length);
} else {
alert('web Storage not supported by your browser.');
}